"""
Therapy session prep brief (skeleton — not implemented).

Goal: produce a single-page, patient-controlled summary of recent behavioral
patterns that the patient can choose to share with their therapist before a
session.

DESIGN PRINCIPLES

1. Patient generates and reviews FIRST — therapist only sees what the
   patient shares.
2. Brief is descriptive, not interpretive. ("Volume of late-night messages
   increased 3x this month" — not "patient appears manic.")
3. Time window is patient-selectable (default: since last session).
4. Patient can redact any item before export.
5. Output formats: PDF, plain text, formatted clipboard.

PROPOSED SECTIONS

Header
- Date range covered
- Patient-provided session date
- Disclaimer: "This is a behavioral overview generated by Pratibmb from the
  patient's own messaging history. It is not a clinical assessment."

Activity overview (no content)
- Total messages sent, vs. previous period
- Distinct conversation partners
- Time-of-day distribution (sleep proxy)
- Notable shifts vs. baseline

Topic surface
- Top 5–10 themes from outgoing messages (LLM-extracted, patient-reviewed)
- Examples: "work stress (mentioned 47 times)", "exercise (12 times, down
  from 38 last month)"

Significant events (LLM-extracted from existing profile)
- New people (first-time conversation partners)
- Lost contacts (people no longer being messaged)
- Travel / location changes (if inferable)
- Major recurring topics emerging or fading

Patient self-annotations
- Free-text field for the patient to add their own context

What was redacted
- Counts only: "3 items in 'romantic relationship' redacted by patient"
- Therapist sees that something was excluded, but not what

OUTPUT SHAPE (proposed)

    SessionBrief(
        period=(start_date, end_date),
        activity=ActivityOverview(...),
        topics=[(theme, mention_count, examples_redacted)],
        events=[Event(...), ...],
        patient_notes=str,
        redactions=[(category, count)],
    )

CLINICAL CAVEATS

- Brief is only as accurate as the message history. If the patient
  primarily uses platforms not yet imported, brief is incomplete.
- Brief reflects communicated experience, not lived experience. Things
  the patient didn't message about are invisible.
- Brief is a starting point for conversation, not a substitute for it.
"""
from __future__ import annotations


def generate_session_brief(*args, **kwargs):
    raise NotImplementedError(
        "Session brief generation is not yet implemented. "
        "See docs/CLINICAL_USE_CASE.md for the proposed clinical extension."
    )
